name: Nix CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    name: Build Nix Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check flake
        run: nix flake check

      - name: Build package
        run: nix build .#default
